### ISSUE TITLE
Show FavIcon for blog

### ISSUE THREAD

**Issue by aldrinjenson** [IEDCMEC/iedc-blog#25]
Would be nice if we could show a [FavIcon](https://en.wikipedia.org/wiki/Favicon) for blog similar to how it's prsent in iedcmec.in

![image](https://user-images.githubusercontent.com/53407417/188057387-59716c3e-772c-4866-b5d4-dcfcc9ec6cfb.png)

Reference: https://github.com/lxndrblz/anatole/pull/33/files

Possible Mentors: @alanphil2k01 

@IEDCMEC/blog-team

**Comment by irfen-mi** [comment]
@aldrinjenson i will add the favicon similar to reference. assign me this task.

**Comment by aldrinjenson** [comment]
@developer-irfan any update on this ?

**Comment by aldrinjenson** [comment]
closed by #36
