### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by aldrinjenson** [IEDCMEC/iedc-blog#26]
![image](https://user-images.githubusercontent.com/53407417/188060466-72e1469b-b0fe-47f7-be6f-c634fce37613.png)

Right now clicking on a link opens it up in the same page. Would be great if you can modify hugo template to have the links open up in new tab when clicked.

[This](https://discourse.gohugo.io/t/how-to-open-plain-url-links-in-a-new-tab/25523/6) thread may help, but you may need to do some trial & error or do some more research if it doesn't work out.

Possible Mentors: @alanphil2k01

**Comment by jaison080** [comment]
The issue has been resolved and the PR has been put up.Do check it and merge...

**Comment by aldrinjenson** [comment]
Oh wow, that was fast! 💯

**Comment by amaldevcd** [comment]
Closed by pr #27
