### ISSUE TITLE
utterances bug

### ISSUE THREAD

**Issue by subru-37** [IEDCMEC/iedc-blog#6]
the same utterances commenting method works in a local clone of anatole theme but it doesn't when the same change is done in our iedc-blog site @adithyaanilkumar @alapanoski @aldrinjenson 
proof that it works in local save
![WhatsApp Image 2022-08-01 at 9 22 33 PM](https://user-images.githubusercontent.com/93091455/182200967-9def0558-8ea8-4389-9bcd-41691c1fb5ff.jpeg)

**Comment by aldrinjenson** [comment]
Hey @subru-37 , the solution mentioned here should help you fix the issue: https://github.com/lxndrblz/anatole/issues/158

edit: Check https://github.com/lxndrblz/anatole/issues/42 as well if you get stuck on the post disappearing from home issue

**Comment by aldrinjenson** [comment]
A gentle helpful tip: Usually when we use an external theme,library or module and get stuck somewhere in using it, chances are some other person would have already faced the same problem. Hence it's a good idea to search the issues tab of the library/theme/module in future to see if people before us has documented the issue and it's solution. This approach has helped me before in past and may be useful to you as well.

Closing this issue now as I think the above mentioned links should solve the problem. Feel free to open up a new issue if the error persists or if the solution above causes some other side-effects.
